// <auto-generated />
namespace NedunyaAntiquesWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TransactionToDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TransactionToDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201809132134295_TransactionToDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
